<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Environment Drift Checker.ApiService\Environment Drift Checker.ApiService.csproj" />
    <ProjectReference Include="..\Environment Drift Checker.Domain\Environment Drift Checker.Domain.csproj" />
    <ProjectReference Include="..\Environment Drift Checker.ServiceDefaults\Environment Drift Checker.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="M5x.MudBlazor" Version="1.10.21.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.10" />
    <PackageReference Include="System.Net.Http.Json" Version="9.0.10" />
  </ItemGroup>

</Project>
